services:
  redactionservice:
    build:
      context: .
      dockerfile: RedactApi\Dockerfile
    ports:
      - "8080:8080" 
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./Logs:/app/Logs # Volume mapping to persist logs outside the container
    restart: always
